services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      users-microservice:
        condition: service_healthy
      posts-microservice:
        condition: service_healthy
    networks:
      - internal-net
    restart: unless-stopped

  users-microservice:
    build:
      context: .
      dockerfile: users/Dockerfile
    container_name: users-microservice
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      app-postgres:
        condition: service_healthy
      users-redis:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - internal-net
    command: uvicorn users.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  app-postgres:
    image: postgres:15
    container_name: app-postgres
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d auth_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  users-redis:
    container_name: users-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - internal-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  posts-microservice:
    build:
      context: .
      dockerfile: posts/Dockerfile
    container_name: posts-microservice
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      app-postgres:
        condition: service_healthy
      users-microservice:
        condition: service_healthy
    networks:
      - internal-net
    command: uvicorn posts.main:app --host 0.0.0.0 --port 8001 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

volumes:
  pgdata:
  redis_data:

networks:
  internal-net:
    driver: bridge